apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-webserver
  namespace: lyonflow
  labels:
    app.kubernetes.io/name: airflow
    release: kps
spec:
  selector:
    matchLabels:
      component: webserver         # label posé par le chart Airflow
      tier: airflow
  namespaceSelector:
    matchNames: [lyonflow]
  endpoints:
    - port: airflow-ui
      path: /admin/metrics
      interval: 60s
      scrapeTimeout: 10s
