- op: replace
  path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
  value: 100Gi
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 8Gi
