apiVersion: v1
kind: Service
metadata:
  name: streamlit
  labels:
    app.kubernetes.io/name: streamlit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: streamlit
  ports:
    - name: http
      port: 8501
      targetPort: 8501
  sessionAffinity: ClientIP   # Streamlit websocket nécessite sticky sessions
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
