apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnn-models
  labels:
    app.kubernetes.io/name: gnn-trainer
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
